export default {
  signature_image_url: 'https://img.guanmai.cn/order_pic/90f6642568c1e456', // 签名图片
  receive_way: 1,
  pick_up_st_name: 'sad',
  pick_up_st_principal: 'hehe',
  pick_up_st_phone: '12314',
  __gm_printer_data_type: 'order',
  real_price: 143.0,
  address_sign: '南山中心区测试地址',
  address_route_name: '路线A',
  driver_phone: '13888888888',
  sid: 'S088888',
  address_sign_id: '30200100000',
  sort_id: 'xxx-8888',
  receive_end_time: '2018-11-15 12:00',
  cname: '测试公司',
  printer_operator: '李四',
  source_origin_id: 'xxx-888',
  freight: 12.0,
  receiver_phone: '13888888888',
  receiver_name: '张三',
  total_pay: 155.0,
  total_self_pick_money: 200,
  total_money: 210,
  all_discount_price: 100,
  before_change_total_pay: 255,
  resname: '测试店铺（深圳总店）',
  res_custom_code: 'QSX12WSX',
  order_security_code: 'PL12041418D3071767665E',
  bill_receiver: '收据人',
  carrier: '测试承运商',
  credit_limit: 100,
  real_address_id: '1001',
  real_resname: '关联分仓名称',
  sale_manager: {
    name: '测试销售经理',
    phone: '13888888888',
    id: 3676,
  },
  id: 'PL8888888',
  refund_money: 0.0,
  receive_begin_time: '2018-11-15 06:00',
  order_process_name: '',
  address_foucus_on: '重点客户',
  combine_goods: [
    {
      money: 1976.4779999999998,
      name: '蔬菜拼盘',
      quantity: 20,
      sale_unit_name: '斤',
      type: 2,
      unit_price: 98,
    },
    {
      money: 9998,
      name: '水果拼盘',
      quantity: 20,
      sale_unit_name: '斤',
      type: 2,
      unit_price: 98,
    },
    {
      money: 66666,
      name: '蔬菜拼盘2',
      quantity: 20,
      sale_unit_name: '斤',
      type: 3,
      unit_price: 66,
    },
  ],
  turnovers: [
    {
      tname: '塑料瓶',
      price: 25.333,
      apply_amount: 200,
      amount: 100,
      total_price: 123.22,
      unit_name: '框',
      sku_name: '蒜头',
    },
    {
      tname: '框',
      price: 25.333,
      apply_amount: 200,
      amount: 100,
      total_price: 123.22,
      unit_name: '个',
      sku_name: '南瓜',
    },
    {
      tname: '盒子',
      price: 25.333,
      apply_amount: 200,
      amount: 100,
      total_price: 123.22,
      unit_name: '箱',
      sku_name: '方便面',
    },
  ],
  refund_new: {
    D7557423_4000: [
      {
        text: '',
        type_text: '规格问题',
        money_delta: 331,
        detail_id: 'D7557423',
        order_detail_id: '4000',
        amount_delta: 253,
        exception_reason_text: '规格问题',
      },
      {
        text: '',
        type_text: '市场缺货',
        money_delta: 24,
        detail_id: 'D7557423',
        order_detail_id: '4000',
        amount_delta: 29,
        exception_reason_text: '市场缺货',
      },
    ],
  },
  no_sku_exceptions: [],
  reward_sku_list: [
    {
      sku_name: '商品名',
      sale_unit: '规格',
      quantity: 111,
      total_cost_point: 222333,
    },
  ],
  details: [
    {
      production_time: '2020-10-12',
      salemenu_price: '1.00',
      rule_type: 2,
      yx_price: 1.333,
      name: '豉油鸡',
      real_item_price_without_tax: '54.00',
      origin_item_price: 54,
      outer_id: '',
      salemenu_id: 'S12731',
      sale_ratio: 1,
      remark: null,
      quantity: 3,
      category_title_1: '熟食类',
      sale_unit_name: '斤',
      supplier_id: 'T13384',
      pinlei_title: '卤制品',
      desc: '',
      spu_name: '豉油鸡',
      total_item_price: 54,
      std_unit_name: '斤',
      sale_price_without_tax: '18.00',
      tax_rate: 0,
      org_item_price: 54,
      saleunit_weighting_quantity: 3,
      std_sale_price_forsale: 18,
      std_sale_price: 18,
      life_time: null,
      specs: '-',
      std_unit_name_forsale: '斤',
      category_title_2: '卤制品',
      is_weigh: false,
      real_is_weight: true,
      real_item_price: 54.6,
      supplier_name: '综合供应商',
      box_list: [],
      org_std_sale_price: 18,
      sale_price: 18,
      is_price_timing: false,
      real_weight: 3,
      purchase_station_id: 'T7936',
      is_set_tax: 0,
      id: 'D7557416',
      tax: '0.00',
      org_sale_price: 18,
      org_std_sale_price_forsale: 18,
      union_dispatch: true,
      outstock_quantity: 10,
      self_pick_money: 20,
      self_pick_quantity: 30,
      origin_purchase_quantity: 3,
      sale_outstock_quantity: -1,
      sale_outstock_price: -3,
      sku_production_date: '2020-12-1',
      before_change_price_forsale: 36,
      before_change_price: 18.5,
      brand: '品牌',
      origin_area: '区域',
      origin_place: '产地',
      specification_desc: '商品规格',
      feature_desc: '商品特征',
      after_sale_desc: '售后标准',
    },
    {
      production_time: null,
      salemenu_price: '1.00',
      sale_outstock_quantity: 1,
      sale_outstock_price: 5,
      name: '卤水猪头皮',
      real_item_price_without_tax: '36.00',
      origin_item_price: 36,
      outer_id: '',
      salemenu_id: 'S12731',
      sale_ratio: 1,
      remark: null,
      quantity: 2,
      category_title_1: '熟食类',
      sale_unit_name: '斤',
      supplier_id: 'T13384',
      pinlei_title: '卤制品',
      desc: '',
      spu_name: '卤水猪头皮',
      total_item_price: 36,
      std_unit_name: '斤',
      sale_price_without_tax: '18.00',
      tax_rate: 0,
      org_item_price: 36,
      saleunit_weighting_quantity: 2,
      std_sale_price_forsale: 18,
      std_sale_price: 18,
      life_time: null,
      specs: '-',
      std_unit_name_forsale: '斤',
      category_title_2: '卤制品',
      is_weigh: false,
      real_is_weight: true,
      real_item_price: 36,
      supplier_name: '综合供应商',
      box_list: [],
      org_std_sale_price: 18,
      sale_price: 18,
      is_price_timing: false,
      real_weight: 2,
      purchase_station_id: 'T7936',
      is_set_tax: 0,
      id: 'D7557423',
      detail_id: '4000',
      tax: '0.00',
      org_sale_price: 18,
      org_std_sale_price_forsale: 18,
      union_dispatch: true,
      outstock_quantity: 10,
      self_pick_money: 20,
      self_pick_quantity: 30,
      origin_purchase_quantity: 3,
      sku_production_date: '2020-12-1',
      before_change_price_forsale: 36,
      before_change_price: 18.5,
      brand: '品牌',
      origin_area: '区域',
      origin_place: '产地',
      specification_desc: '商品规格',
      feature_desc: '商品特征',
      after_sale_desc: '售后标准',
    },
    {
      production_time: null,
      salemenu_price: '1.00',

      name: '烧肉|块',
      real_item_price_without_tax: '36.00',
      origin_item_price: 72,
      outer_id: '',
      salemenu_id: 'S12731',
      sale_ratio: 2,
      remark: null,
      quantity: 2,
      category_title_1: '熟食类',
      sale_unit_name: '块',
      supplier_id: 'T13384',
      pinlei_title: '烧腊',
      desc: '',
      spu_name: '烧肉',
      total_item_price: 72,
      std_unit_name: '斤',
      sale_price_without_tax: '36.00',
      tax_rate: 0,
      org_item_price: 36,
      saleunit_weighting_quantity: 2,
      std_sale_price_forsale: 18,
      std_sale_price: 18,
      life_time: null,
      specs: '约2.0斤/块',
      std_unit_name_forsale: '斤',
      category_title_2: '烧腊',
      is_weigh: true,
      real_is_weight: true,
      real_item_price: 36,
      supplier_name: '综合供应商',
      box_list: [],
      org_std_sale_price: 18,
      sale_price: 36,
      is_price_timing: false,
      real_weight: 2,
      purchase_station_id: 'T7936',
      is_set_tax: 0,
      id: 'D7557482',
      tax: '0.00',
      org_sale_price: 36,
      org_std_sale_price_forsale: 18,
      union_dispatch: true,
      outstock_quantity: 10,
      self_pick_money: 20,
      self_pick_quantity: 30,
      origin_purchase_quantity: 3,
      sku_production_date: '2020-12-1',
      before_change_price_forsale: 72,
      before_change_price: 18.5,
      brand: '品牌',
      origin_area: '区域',
      origin_place: '产地',
      specification_desc: '商品规格',
      feature_desc: '商品特征',
      after_sale_desc: '售后标准',
    },
    {
      production_time: null,
      salemenu_price: '1.00',

      name: '熟牛筋',
      real_item_price_without_tax: '18.00',
      origin_item_price: 18,
      outer_id: '',
      salemenu_id: 'S12731',
      sale_ratio: 1,
      remark: null,
      quantity: 1,
      category_title_1: '熟食类',
      sale_unit_name: '斤',
      supplier_id: 'T13384',
      pinlei_title: '其他熟食',
      desc: '',
      spu_name: '熟牛筋',
      total_item_price: 18,
      std_unit_name: '斤',
      sale_price_without_tax: '18.00',
      tax_rate: 0,
      org_item_price: 18,
      saleunit_weighting_quantity: 1,
      std_sale_price_forsale: 18,
      std_sale_price: 18,
      life_time: null,
      specs: '-',
      std_unit_name_forsale: '斤',
      category_title_2: '其他熟食',
      is_weigh: false,
      real_is_weight: true,
      real_item_price: 18,
      supplier_name: '综合供应商',
      box_list: [],
      org_std_sale_price: 18,
      sale_price: 18,
      is_price_timing: false,
      real_weight: 1,
      purchase_station_id: 'T7936',
      is_set_tax: 0,
      id: 'D7557460',
      detail_id: '5500',
      tax: '0.00',
      org_sale_price: 18,
      org_std_sale_price_forsale: 18,
      union_dispatch: true,
      outstock_quantity: 10,
      self_pick_money: 20,
      self_pick_quantity: 30,
      origin_purchase_quantity: 3,
      sku_production_date: '2020-12-1',
      before_change_price_forsale: 36,
      before_change_price: 18.5,
      brand: '品牌',
      origin_area: '区域',
      origin_place: '产地',
      specification_desc: '商品规格',
      feature_desc: '商品特征',
      after_sale_desc: '售后标准',
    },
    {
      production_time: null,
      salemenu_price: '1.00',

      name: '利苑叉烧|包',
      real_item_price_without_tax: '108.00',
      origin_item_price: 36,
      outer_id: '',
      salemenu_id: 'S12731',
      sale_ratio: 2,
      remark: null,
      quantity: 1,
      category_title_1: '熟食类',
      sale_unit_name: '包',
      supplier_id: 'T13384',
      pinlei_title: '烧腊',
      desc: '',
      spu_name: '利苑叉烧',
      total_item_price: 36,
      std_unit_name: '斤',
      sale_price_without_tax: '36.00',
      tax_rate: 0,
      org_item_price: 108,
      saleunit_weighting_quantity: 1,
      std_sale_price_forsale: 18,
      std_sale_price: 18,
      life_time: null,
      specs: '约2.0斤/包',
      std_unit_name_forsale: '斤',
      category_title_2: '烧腊',
      is_weigh: true,
      real_is_weight: true,
      real_item_price: 108,
      supplier_name: '综合供应商',
      box_list: [],
      org_std_sale_price: 18,
      sale_price: 36,
      is_price_timing: false,
      real_weight: 6,
      purchase_station_id: 'T7936',
      is_set_tax: 0,
      id: 'D7557503',
      tax: '0.00',
      org_sale_price: 36,
      org_std_sale_price_forsale: 18,
      union_dispatch: true,
      outstock_quantity: 10,
      self_pick_money: 20,
      self_pick_quantity: 30,
      origin_purchase_quantity: 3,
      sku_production_date: '2020-12-1',
      before_change_price_forsale: 72,
      before_change_price: 18.5,
      brand: '品牌',
      origin_area: '区域',
      origin_place: '产地',
      specification_desc: '商品规格',
      feature_desc: '商品特征',
      after_sale_desc: '售后标准',
    },
  ],
  tax_number: 1,
  exception_new: {
    D7557460_5500: [
      {
        text: '原因',
        type_text: '规格问题',
        money_delta: 1,
        detail_id: 'D7557460',
        amount_delta: 2,
        exception_reason_text: '规格问题',
      },
      {
        text: '测试原因',
        type_text: '市场缺货',
        money_delta: 1,
        detail_id: 'D7557460',
        amount_delta: 3,
        exception_reason_text: '规格问题',
      },
    ],
  },
  settle_way: 1,
  bill_address: '收据地址',
  abnormal_money: 0.0,
  area_l2: '南山中心区测试地址',
  area_l1: '南山区',
  total_price: 143.0,
  coupon_amount: 5.0,
  order_box_count: 4,
  child_sort_id: '',
  driver_name: '李四',
  city: '深圳市',
  sales_name: '测试人',
  origin_customer: {},
  address: '南山大道12号测试地址',
  remark: '测试订单备注',
  username: '黎明xxx',
  pay_method: {
    cycle_length: null,
    begin_day: null,
    settle_day: null,
    pay_method: 1,
  },
  create_user: '测试下单员',
}
