export default {
  __gm_printer_data_type: 'order',
  receive_end_time: '2020-05-26 06:00',
  real_price: '8101.36',
  id: 'PL16145681',
  max_load: '',
  turnovers: [
    {
      tname: '塑料瓶',
      price: 25.333,
      apply_amount: 200,
      amount: 100,
      total_price: 123.22,
      unit_name: '框'
    },
    {
      tname: '豆腐',
      price: 25.333,
      apply_amount: 200,
      amount: 100,
      total_price: 123.22,
      unit_name: '个'
    },
    {
      tname: '盒子',
      price: 25.333,
      apply_amount: 200,
      amount: 100,
      total_price: 123.22,
      unit_name: '箱'
    }
  ],
  combine_goods: [
    {
      money: 1976.4779999999998,
      name: '蔬菜拼盘',
      quantity: 20,
      sale_unit_name: '斤',
      type: 2,
      unit_price: 98.8239
    },
    {
      money: 9998,
      name: '水果拼盘',
      quantity: 20,
      sale_unit_name: '斤',
      type: 2,
      unit_price: 98
    },
    {
      money: 66666,
      name: '蔬菜拼盘2',
      quantity: 20,
      sale_unit_name: '斤',
      type: 3,
      unit_price: 66
    }
  ],
  details: Array(180)
    .fill(1)
    .map((o, index) => ({
      org_std_sale_price_forsale: 48.0,
      id: 'D14442448',
      std_unit_name_forsale: '斤',
      real_item_price_without_tax: '96.00',
      pinlei_title: '干果蜜饯',
      salemenu_price: '48.00',
      purchase_station_id: 'T23299',
      sale_price_without_tax: '48.00',
      spu_name: '特级枸杞',
      is_price_timing: false,
      desc:
        '养肝，滋肾，润肺。枸杞子被卫生部列为"药食两用"品种，枸杞子可以加工成各种食品、饮料、保健酒、保健品等等。在煲汤或者煮粥的时候也经常加入枸杞。\n',
      total_item_price: 96.0,
      tax: '0.00',
      real_weight: 2.0,
      std_sale_price: 48.0,
      category_title_2: '干果蜜饯',
      category_id_1: 'A1648',
      supplier_name: '标品有库存',
      tax_rate: 0.0,
      real_is_weight: true,
      is_set_tax: 0,
      remark: null,
      outer_id: null,
      std_unit_name: '斤',
      life_time: null,
      org_item_price: 96.0,
      std_sale_price_forsale: 48.0,
      saleunit_weighting_quantity: 2.0,
      sale_price: 48.0,
      specs: '-',
      org_std_sale_price: 48.0,
      production_time: null,
      origin_item_price: 96.0,
      supplier_id: 'T37875',
      category_title_1: '粮油干货',
      real_item_price: 96.0,
      is_weigh: true,
      sale_unit_name: '斤',
      salemenu_id: 'S19516',
      org_sale_price: 48.0,
      sale_ratio: 1.0,
      box_list: [],
      union_dispatch: true,
      quantity: 2.0,
      name:
        '特级枸杞' + (index < 120 && index > 40 ? Array(14).fill('fuck') : '')
    })),
  abnormal_money: '720.00',
  city: '西安市',
  driver_phone: '',
  signature_image_url: '',
  bill_address: null,
  total_pay: '8821.36',
  area_l1: '长安区',
  area_l2: '南大学城',
  resname: '雅居乐小学',
  abnormals: Array(0).fill({
    type_text: '其它',
    money_delta: 720.0,
    text: '5月25日送爱菊中筋特一粉3袋×105=315\n爱菊特粳米3袋×135=405\n',
    amount_delta: 0,
    detail_id: '0'
  }),
  template_id: 358,
  order_box_count: 0,
  receiver_phone: '18729018993',
  source_origin_id: '',
  tax_number: 526702,
  refunds: [],
  sale_manager: { id: 2148, phone: '', name: '薛剑文' },
  address: '陕西省西安市长安区郭杜街道樱花一路铂琅峯南门西侧西电附小雅居乐分校',
  total_tax: '0.00',
  child_sort_id: '',
  refund_money: '0.00',
  origin_customer: {},
  address_sign: '南大学城',
  bill_receiver: null,
  date_time: '2020-05-25 16:57:47',
  username: 'yjlxx',
  remark: null,
  address_route_name: 'A大客户',
  receiver_name: '田老师',
  receive_way: 1,
  coupon_amount: '-0.00',
  order_process_name: '',
  pay_method: {
    cycle_length: null,
    begin_day: 1,
    settle_day: 26,
    pay_method: 3
  },
  total_price: '8043.10',
  sid: '906269',
  credit_limit: 0.0,
  res_custom_code: '',
  driver_name: '',
  settle_way: 1,
  address_sign_id: '3271000500000',
  plate_number: '',
  sort_id: 'E（临）-18-1',
  carrier: '',
  car_model: '未指定车型',
  receive_begin_time: '2020-05-26 05:30',
  cname: '',
  uid: '926692',
  pay_status: 1,
  create_user: 'xchengjr',
  distributor_id: 0,
  freight: '0.00',
  sales_name: '薛剑文'
}
