const data = {
  'sales_name': '',
  'carrier': '',
  'sort_id': '',
  'date_time': '2018-07-06 15:58:24',
  'receiver_phone': '15898745878',
  'receive_begin_time': '2018-07-07 07:00',
  'settle_way': 1,
  'area_l2': '华强北',
  'abnormals': [],
  'details': [
    {
      'union_dispatch': true,
      'spu_name': '宽叶菠',
      'sale_price_without_tax': '0.33',
      'is_price_timing': false,
      'salemenu_id': 'S7536',
      'tax_rate': 0,
      'pinlei_title': '菠菜',
      'real_weight': 3,
      'remark': null,
      'id': 'D4363441',
      'origin_item_price': 2,
      'sale_unit_name': '包',
      'desc': '',
      'real_item_price_without_tax': '1.00',
      'sale_price': 1,
      'real_is_weight': true,
      'std_unit_name': '斤',
      'sale_ratio': 3,
      'category_title_1': '蔬菜',
      'is_weigh': false,
      'category_title_2': '叶菜',
      'specs': '约3.0斤/包',
      'quantity': 1,
      'outer_id': '',
      'name': '宽叶菠|测试',
      'total_item_price': 1,
      'std_sale_price': 0.33,
      'purchase_station_id': 'T10001',
      'real_item_price': 1,
      'tax': '0.00'
    }
  ],
  'cname': '',
  'address': '范德萨范德萨范德萨范德萨范德萨',
  'remark': null,
  'id': 'PL2223711',
  'sale_manager': {
    'id': null,
    'phone': null,
    'name': null
  },
  'address_sign': '华强北',
  'origin_customer': {},
  'sid': '62175',
  'address_sign_id': '30100100000',
  'receiver_name': 'xjxc001',
  'refunds': [],
  'abnormal_money': 0,
  'area_l1': '福田区',
  'real_price': 1,
  'driver_name': '',
  'child_sort_id': '',
  'city': '深圳市',
  'receive_end_time': '2018-07-07 11:30',
  'freight': 0,
  'refund_money': 0,
  'total_pay': 1,
  'resname': 'xjxc001',
  'source_origin_id': '',
  'driver_phone': '',
  'total_price': 1
}

export default data
